// Generated by CoffeeScript 1.12.7
var base64CustomFavicon, newFaviconElement, oldFaviconElement, ref, ref1, ref2, ref3;

if (ez5.version("6")) {
  if ((ref = ez5.session.config.base.plugin) != null ? ref['custom-favicon'] : void 0) {
    if ((ref1 = ez5.session.config.base.plugin['custom-favicon']) != null ? (ref2 = ref1.config) != null ? (ref3 = ref2.custom_favicon) != null ? ref3.image_as_base64 : void 0 : void 0 : void 0) {
      base64CustomFavicon = ez5.session.config.base.plugin['custom-favicon'].config.custom_favicon.image_as_base64;
      if (base64CustomFavicon !== '') {
        console.log("%c Welcome favicon.", "padding: 14px 0px 10px 45px; background-image: url('" + base64CustomFavicon + "'); background-repeat: no-repeat; background-position: left center; background-size: 30px auto");
        oldFaviconElement = document.querySelector("link[rel*='icon']");
        oldFaviconElement.remove();
        newFaviconElement = document.createElement('link');
        newFaviconElement.type = 'image/x-icon';
        newFaviconElement.rel = 'shortcut icon';
        newFaviconElement.href = base64CustomFavicon;
        document.getElementsByTagName('head')[0].appendChild(newFaviconElement);
      }
    }
  }
}
